export type { ClientMessage } from '~/protocol/client'
export type { ServerMessage } from '~/protocol/server'
export type { Vec2 } from '~/protocol/shared'
export type { Player } from '~/game/player'
export type { MapObject } from '~/maps'
export type { GameObject } from '~/game_objects'