services:
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
            MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 38081:8081
        environment:
            ME_CONFIG_BASICAUTH: $BASIC_AUTH
            ME_CONFIG_BASICAUTH_USERNAME: $BASIC_AUTH_USERNAME
            ME_CONFIG_BASICAUTH_PASSWORD: $BASIC_AUTH_PASSWORD
            ME_CONFIG_MONGODB_ADMINUSERNAME: $ADMIN_USERNAME
            ME_CONFIG_MONGODB_ADMINPASSWORD: $ADMIN_PASSWORD
            ME_CONFIG_MONGODB_URL: $DB_CONN_STRING
    server:
        build: .
        restart: always
        ports:
            - $LISTEN_PORT:8000
        depends_on:
            - mongo
        environment:
            SERVER_PORT: 8000
            RELEASE_SOURCE: $RELEASE_SOURCE
            DB_CONN_STRING: $DB_CONN_STRING
            DB_NAME: $DB_NAME
            SCOREBOARD_URL: $SCOREBOARD_URL
            SCOREBOARD_TOKEN: $SCOREBOARD_TOKEN
            CHALLENGE_IDS: $CHALLENGE_IDS
            DEBUG: $DEBUG
            VISUALIZER_URL: $VISUALIZER_URL
