services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    # for development
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $ADMIN_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $ADMIN_PASSWORD
      ME_CONFIG_MONGODB_URL: $DB_CONN_STRING
  server:
    build: .
    restart: always
    ports:
      - 8001:8000
    depends_on:
      - mongo
    environment:
      SERVER_PORT: 8000
      DB_CONN_STRING: $DB_CONN_STRING
