services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: peko
      MONGO_INITDB_ROOT_PASSWORD: miko
    # for development
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: peko
      ME_CONFIG_MONGODB_ADMINPASSWORD: miko
      ME_CONFIG_MONGODB_URL: mongodb://peko:miko@mongo:27017/
  # server: TBD
